name: Lint and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
      - uses: leafo/gh-actions-luarocks@v4
      - name: dependencies
        run: |
          cargo install stylua
          luarocks install busted
      - name: Check format
        run: make format
      - name: Run tests
        run: make test
