name: Lint and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: '5.1.5'
      - name: dependencies
        run: |
          cargo install stylua
          luarocks install busted
      - name: Check format
        run: make format
      - name: Run tests
        run: make test
